[package]
name = "hybrid-indexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
futures = "0.3.26"
hex = "0.4.3"
parity-scale-codec = "3.4.0"
serde_json = "1.0.94"
sled = "0.34.7"
subxt = "0.27.1"
tokio = { version = "1.26.0", features = ["full"] }
tokio-tungstenite = "0.18.0"
